version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: intel-stealer-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - intel-net
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: intel-stealer-backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      PORT: 3000
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
    volumes:
      - ./backend/data:/app/data
    networks:
      - intel-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: intel-stealer-frontend
    depends_on:
      - backend
    networks:
      - intel-net
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: intel-stealer-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - intel-net
    restart: unless-stopped

networks:
  intel-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
